version: '3'

services:
  master:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root

  slave:
     image: mysql:5.7
     ports:
       - "3307:3306"
     restart: always
     volumes:
      - "./slave/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./slave/slave.sql:/docker-entrypoint-initdb.d/slave.sql"
      - "./slave/data:/var/lib/mysql"
     environment:
      MYSQL_ROOT_PASSWORD: root
